<script setup lang="ts">
import {ref} from "vue";

const activeTab = ref(0);
const activeSubTab = ref(0);

const panelTabs = [
    {name: "Basics", activeId: 0},
    {name: "Pages", activeId: 1},
    {name: "Components", activeId: 2},
    {name: "Models", activeId: 3},
    {name: "Data", activeId: 4}
]
const basicsLinks = [
    {name: "Introduction", activeId: 0},
    {name: "Vue 3 + Vite + NPM", activeId: 1},
    {name: "Bulma", activeId: 2},
    {name: "Dummy json", activeId: 3},
    {name: "FortAwesome", activeId: 4}
]
const pagesLinks = [
    {name: "Home Page", activeId: 5},
    {name: "Friend's Activity", activeId: 6},
    {name: "My Activity + Users", activeId: 7},
    {name: "Statistics", activeId: 8},
    {name: "Documentation", activeId: 9}
]
const componentsLinks = [
    {name: "NavBar", activeId: 10},
    {name: "WorkoutBox", activeId: 11},
    {name: "StatsBox", activeId: 12},
    {name: "AddWorkoutModal", activeId: 13},
    {name: "LoginModal", activeId: 14},
    {name: "SignupTextField", activeId: 15},
    {name: "WorkoutTextField", activeId: 16}
]
const modelsLinks = [
    {name: "Workout", activeId: 17},
    {name: "Stats", activeId: 18},
    {name: "User", activeId: 19},
    {name: "Globals", activeId: 20},
    {name: "TextField", activeId: 21}
]
const dataLinks = [
    {name: "Workouts", activeId: 22},
    {name: "Stats", activeId: 23},
    {name: "Users", activeId: 24},
    {name: "Globals", activeId: 25},
    {name: "TextFields", activeId: 26}
]
const docs = [
    {
        title: "Introduction",
        content: "This is the final project for Web Server Programming 2024. This has been a gigantic pain at times, but I feel like I'm learning a lot. I'm excited to see how it turns out, once I have a server to pair with it, and I kill all the stupid bugs."
    },
    {
        title: "Vue 3 + Vite + NPM",
        content: "This project uses Vue 3 as its framework. The ability to componentize everything is really nice. I'm not sure if I'm using it to its full potential, in fact, I'm certain I'm not, but I'm happy with how it's turned out so far. Vite is the build tool I'm using. It makes testing so much better because of hot module reloading. NPM is the package manager I'm using. It's been nothing but a pleasure to work with, especially since I figured out how to make a WebStorm run configuration that would start my dev server without needing the CLI. Yes, I'm exactly that lazy."
    },
    {
        title: "Bulma",
        content: "I'm using Bulma for my CSS framework. Bulma makes it so that I dont have to do that much CSS, although I'm using quite a bit more than I had planned. I'm using a custom CSS file to override some of the default Bulma styles, because I don't like that Bulma doesn't have any sort of built in dark mode. As a person who can't bear having his eyes burned out every time he looks at a screen, I need dark mode. The only real area's where I overruled Bulma was in colors. Vite scaffolded the project with a lot of boilerplate CSS, and I modified that to fit my needs. I also added a few custom classes to make my life easier. I didn't really want to overwrite the Bulma File, so I made 'dcs', 'ics', and 'scs', for Default Color Scheme, Input Color Scheme, and Secondary Color Scheme, respectively. I also added 'bordered' to make it so that I could have a consistent border on any element I wanted."
    },
    {
        title: "Dummy json",
        content: "All the fake json data in users was generated by Dummy json, with slight modifications so I could put myself in, and create an admin field. The only purpose of the admin field for now is to determine whether or not the user can access the users page. I'm certain that I'll find more uses for it later."
    },
    {
        title: "FortAwesome",
        content: "All the little icons you see are from FortAwesome. All the ones you don't see, or don't make any sense, are because FortAwesome has been giving me pain for nearly a month now. I'm sure I'll get it eventually, but for now, it is what it is."
    },
    {
        title: "Home Page",
        content: "This is the page that you see immediately on connecting. I'm extremely happy with how it has turned out. I was a little apprehensive about the secondary color, since my original plan was to stick to a very stark black and white color scheme, but I think it looks great. I'm also happy with the way the stats box turned out, but there is more on them in the StatsBox component documentation."
    },
    {
        title: "Friend's Activity",
        content: "This is the friend's activity page. For now, since there isn't any way to find people, or to 'friend them', it just shows all the users. That will change once I have a method for finding users, and a method for friending them."
    },
    {
        title: "My Activity + Users",
        content: "This is the my activity page. It shows all activities for the Logged In User. Unfortunately, I don't have a method for logging in yet, so it defaults to me, so you can see the users page. The users page is just a list of all the users, but the link only works if the Logged In User is an admin. Since i don't have a method for logging in, the default user is me, who is an admin. if you go into the Globals.ts file, you can change the Logged In User to be a non-admin, and then the link won't work."
    },
    {
        title: "Statistics",
        content: "This is the statistics page. This was sup"
    },
    {
        title: "Documentation",
        content: "This is the documentation page."
    },
    {
        title: "NavBar",
        content: "This is the nav bar component."
    },
    {
        title: "WorkoutBox",
        content: "This is the workout box component."
    },
    {
        title: "StatsBox",
        content: "This is the stats box component."
    },
    {
        title: "AddWorkoutModal",
        content: "This is the add workout modal component."
    },
    {
        title: "LoginModal",
        content: "This is the login modal component."
    },
    {
        title: "SignupTextField",
        content: "This is the signup text field component."
    },
    {
        title: "WorkoutTextField",
        content: "This is the workout text field component."
    },
    {
        title: "Workout",
        content: "This is the workout model."
    },
    {
        title: "Stats",
        content: "This is the stats model."
    },
    {
        title: "User",
        content: "This is the user model."
    },
    {
        title: "Globals",
        content: "This is the globals model."
    },
    {
        title: "TextField",
        content: "This is the text field model."
    },
    {
        title: "Workouts",
        content: "This is the workouts data."
    },
    {
        title: "Stats",
        content: "This is the stats data."
    },
    {
        title: "Users",
        content: "This is the users data."
    },
    {
        title: "Globals",
        content: "This is the globals data."
    },
    {
        title: "TextFields",
        content: "This is the text fields data."
    }
]


</script>

<template>
    <div class="columns is-centered">
        <div class="column is-half">
            <nav class="panel dcs bordered">
                <p class="panel-tabs dcs">
                    <a v-for="tab in panelTabs" :class="activeTab === tab.activeId && 'is-active'"
                       class="dcs is-hovered-mute" @click="activeTab = tab.activeId">{{ tab.name }}</a>
                </p>
                <div v-if="activeTab === 0">
                    <a v-for="link in basicsLinks" :class="activeSubTab === link.activeId && 'is-active'"
                       class="dcs is-hovered-mute panel-block" @click="activeSubTab = link.activeId">{{ link.name }}</a>
                </div>
                <div v-if="activeTab === 1">
                    <a v-for="link in pagesLinks" :class="activeSubTab === link.activeId && 'is-active'"
                       class="dcs is-hovered-mute panel-block" @click="activeSubTab = link.activeId">{{ link.name }}</a>
                </div>
                <div v-if="activeTab === 2">
                    <a v-for="link in componentsLinks" :class="activeSubTab === link.activeId && 'is-active'"
                       class="dcs is-hovered-mute panel-block" @click="activeSubTab = link.activeId">{{ link.name }}</a>
                </div>
                <div v-if="activeTab === 3">
                    <a v-for="link in modelsLinks" :class="activeSubTab === link.activeId && 'is-active'"
                       class="dcs is-hovered-mute panel-block" @click="activeSubTab = link.activeId">{{ link.name }}</a>
                </div>
                <div v-if="activeTab === 4">
                    <a v-for="link in dataLinks" :class="activeSubTab === link.activeId && 'is-active'"
                       class="dcs is-hovered-mute panel-block" @click="activeSubTab = link.activeId">{{ link.name }}</a>
                </div>
            </nav>
            <div class="box dcs bordered">
                <h1 class="is-size-1 has-text-weight-bold dcs">Documentation</h1>
                <p class="dcs">
                    This is the documentation page. Here you can find all the information you need to use the
                    application.
                </p>
                <hr class="navbar-divider">
                <div class="dcs">
                    <h2 class="is-size-2 has-text-weight-bold dcs">{{ docs[activeSubTab].title }}</h2>
                    <div class="dcs">
                        {{ docs[activeSubTab].content }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<style scoped>
a.is-active {
    color: var(--color-primary-hover) !important;
}
</style>